# Generated by Django 4.1.3 on 2022-12-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biodata',
        ),
    ]
