# Generated by Django 4.1.3 on 2022-12-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_filem_delete_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Filem',
            },
        ),
        migrations.DeleteModel(
            name='Filem',
        ),
    ]
