# Generated by Django 4.1.3 on 2022-12-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_api_delete_filem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name_plural': 'API'},
        ),
    ]
