# Generated by Django 4.1.3 on 2022-12-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_api_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='api_key',
            new_name='key',
        ),
    ]
