# Generated by Django 4.1.3 on 2022-12-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_api_filem_alter_filem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Komentar',
            },
        ),
    ]
