# Generated by Django 4.1.3 on 2022-12-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_options_rename_created_on_comment_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Komen',
        ),
    ]
