# Generated by Django 4.1.3 on 2022-12-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_artikel_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
