# Generated by Django 4.1.3 on 2022-12-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
