# Generated by Django 4.1.3 on 2022-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_artikel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
