# Generated by Django 4.1.3 on 2022-12-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_artikel_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
