# Generated by Django 4.1.3 on 2022-12-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_rename_body_comment_komen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
