# Generated by Django 4.1.3 on 2022-12-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_comment_options_remove_comment_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
