# Generated by Django 4.1.3 on 2022-12-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filem',
        ),
    ]
