# Generated by Django 4.1.3 on 2022-12-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_filem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filem',
            name='poster_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
