# Generated by Django 4.1.3 on 2022-12-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_filem_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filem',
            name='poster_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
