# Generated by Django 4.1.3 on 2022-12-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_filem_poster_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filem',
            old_name='overview',
            new_name='release_date',
        ),
    ]
