# Generated by Django 4.1.3 on 2022-12-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_rename_overview_filem_release_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filem',
        ),
    ]
