# Generated by Django 4.1.3 on 2022-12-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_delete_filem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('poster_path', models.ImageField(blank=True, null=True, upload_to='')),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(max_length=100)),
                ('vote_average', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Filem',
            },
        ),
    ]
