# Generated by Django 4.1.3 on 2022-12-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_filem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='artikel',
        ),
    ]
