# Generated by Django 4.1.3 on 2022-12-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_rename_post_comment_artikel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
