# Generated by Django 4.1.3 on 2022-12-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_alter_artikel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
